name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: yitech/lynkora-web-page:latest
        platforms: linux/amd64,linux/arm64/v8

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop lynkora-web-page || true
          docker rmi yitech/lynkora-web-page:latest
          docker pull yitech/lynkora-web-page:latest
          docker run -p 80:80 --rm --name lynkora-web-page --network lynkora -d yitech/lynkora-web-page